# Generated by Django 4.0.2 on 2022-02-23 09:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=128)),
                ('inches', models.FloatField()),
                ('screen_width', models.IntegerField()),
                ('screen_height', models.IntegerField()),
                ('cpu', models.CharField(max_length=512)),
                ('ram', models.IntegerField()),
                ('memory1_storage', models.IntegerField()),
                ('memory1_type', models.CharField(max_length=128)),
                ('memory2_storage', models.IntegerField(blank=True, null=True)),
                ('memory2_type', models.CharField(blank=True, max_length=128, null=True)),
                ('gpu', models.CharField(max_length=512)),
                ('os', models.CharField(max_length=128)),
                ('weight_kg', models.CharField(max_length=128)),
                ('price_euro', models.FloatField()),
                ('stock_amount', models.IntegerField(max_length=128, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_date', models.DateField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lapotp_app.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('item_price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lapotp_app.laptop')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lapotp_app.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='laptop',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lapotp_app.manufacurer'),
        ),
    ]
