# Generated by Django 4.0.2 on 2022-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapotp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_laptops',
            field=models.ManyToManyField(through='lapotp_app.OrderItems', to='lapotp_app.Laptop'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='laptop',
            table='laptops',
        ),
        migrations.AlterModelTable(
            name='manufacurer',
            table='manufactorer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderitems',
            table='order_items',
        ),
    ]
