# Generated by Django 4.0.2 on 2022-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapotp_app', '0003_alter_laptop_memory1_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='memory1_GOT',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='memory2_GOT',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='memory1_storage',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='memory2_storage',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
