# Generated by Django 4.0.2 on 2022-02-28 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapotp_app', '0005_alter_customer_created_at_alter_laptop_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='manufacurer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='manufacurer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='stock_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(blank=True, null=True)),
                ('review_title', models.CharField(max_length=128)),
                ('review_content', models.CharField(max_length=515)),
                ('laptop_grade', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=128)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lapotp_app.laptop')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lapotp_app.customer')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
