# Generated by Django 4.0.2 on 2022-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapotp_app', '0006_remove_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='laptop_grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=128),
        ),
    ]
